# Название окружения
name: ml-course-brunoyam
channels:
  # Репозитории, из которых будут подтягиваться пакеты
  - conda-forge
  - anaconda
dependencies:
  # Используемые пакеты
  - numpy
  - pandas
  - matplotlib
  - plotly
  - scikit-learn==1.0.1
  - seaborn
  - statsmodels
